### ISSUE TITLE
Does not work on Android 4.3

### ISSUE THREAD

**Issue by marchip** [pauldmps/Android-pdf.js#1]
Hi,
I tested with android 4.3 and I got the following error:
<code>
08-19 11:56:57.691: I/Web Console(7597): Warning: Unhandled rejection: RangeError: ArrayBuffer length minus the byteOffset is not a multiple of the element size.
08-19 11:56:57.691: I/Web Console(7597):     at Object.MurmurHash3_64_update [as update](file:///android_asset/pdfviewer/pdf.worker.js:42657:29)
</code>

With Android 4.4 works.
Could you check and correct this error? I would be grateful.
Thanks

**Comment by lcopley** [comment]
I had a similar problem (with the same error message) and imported the latest version (1.1.something) of PDF.js and pdf.worker.js with good results...in Android 4.3 on my phone  When I try it with an Android 4.3 AVD 10.1" tablet, I get no page numbers but I do get the "Page /" at the top and this message:

07-15 13:41:05.014    4365-4365/com.sample.pdfwebviewer I/Web Console﹕ Warning: Unhandled rejection: UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "file:///storage/sdcard/data/test.pdf".
    Error
            at UnexpectedResponseExceptionClosure (file:///android_asset/pdfviewer/pdf.js:421:43)
            at pdfjsWrapper (file:///android_asset/pdfviewer/pdf.js:425:3)
            at file:///android_asset/pdfviewer/pdf.js:7998:4 at file:///android_asset/pdfviewer/pdf.js:235

I checked; it's the same binary for both.  

Any idea what might have happened? All I can think is that the asset location in one is not in the same location in the other, but if they are the same deployment, what happened?
